Update error msg for passwd-protected PDF
alephdata/ingest-file pull request #417
Opened 2023-01-16 12:24 UTC by catileptic

* change public-facing error message to something more explicit
* log other types of errors that might arise

2023-01-16 13:18 UTC, stchris requested changes

2023-01-16 13:18 UTC, stchris commented on ingestors/documents/pdf.py
> +            log.info(f"Failed to ingest PDF: {file_path}. Reason: {ex}.")
You could use the [exception](https://docs.python.org/3/library/logging.html#logging.Logger.exception) method on the logger, which will print the stack trace as well.

2023-01-16 13:18 UTC, stchris commented on ingestors/documents/pdf.py
> +            raise ProcessingException("Could not extract PDF file.")
Did you intentionally remove the `from ex` from the end of the line here? I think it's generally a good idea to pass the exception up the stack.

2023-01-16 13:44 UTC, stchris reviewed
One more minor comment

2023-01-16 13:54 UTC, stchris approved these changes
Woohoo, thanks for fixing this!

2023-01-17 12:19 UTC, tillprochaska commented on ingestors/documents/pdf.py
> +                "Could not extract PDF file. The PDF is protected with a password. Try removing the password protection and re-ingesting the documents."
As this error message will be surfaced to end users, maybe we could use "reupload" instead of "reingest"?

2023-01-18 14:39 UTC, closed without merging